### PR TITLE
feat:find word #107

### PR DESCRIPTION
**Pull request by Emeka-Ugbanu-hub**
added the find and highlight feature

### CODE REVIEW

**Comment by Emeka-Ugbanu-hub** [comment]
added the find and highlight feature

**Comment by Muhammed-Rahif** [comment]
I am a little busier these days, will do a review before 5/2/2022, I hope
so. Thanks for your valuable contribution, I appreciate it 🎀!

**Comment by Emeka-Ugbanu-hub** [comment]
ok Thanks

**Comment by Muhammed-Rahif** [comment]
It's working fine... But I did notice to make some improvements, I will do it for you!

**Review by Muhammed-Rahif — COMMENTED** [review]
It's working fine... But I did notice to make some improvements, I will do it for you!

**Comment by Emeka-Ugbanu-hub** [comment]
Ok thanks

**Comment by Emeka-Ugbanu-hub** [comment]
@Muhammed-Rahif have you made the imorovements

**Comment by Emeka-Ugbanu-hub** [comment]
just wanted to remind you that the pull request hasn't been merged yet

**Comment by Emeka-Ugbanu-hub** [comment]
still wanted to remind you that the pull request hasn't been merged

**Comment by Muhammed-Rahif** [comment]
Hi @Emeka-Ugbanu-hub,

Thank you for your contribution to this project. Unfortunately, due to unforeseen circumstances, this project has been inactive for the past few months. We apologize for any inconvenience this may have caused.

We've recently switched the technology stack of this project from ReactJS to NextJS. As a result, some of the pull requests related to the old stack may no longer be applicable. After reviewing your pull request, we've determined that it is related to the old stack, and we won't be able to merge it.

We've deployed the new version of the app to production, and you can access it at this link: **[https://notepad-dusky.vercel.app/](https://notepad-dusky.vercel.app/)**

I would like to take this opportunity to encourage you to actively contribute to the project. If you have any ideas, feature requests, or bug reports, please don't hesitate to create a new issue or submit a pull request on our [GitHub repository](https://github.com/Muhammed-Rahif/Notepad).

Thank you, @Emeka-Ugbanu-hub, for your understanding and for your interest in this project! Let's work together to bring it back to life.

Best regards,  
Muhammed Rahif

**Pull request closed without merging**
