### PR TITLE
GitHub link Added

### PR DESCRIPTION
**Pull request by khushbooag4**
I have added the options of Github on the help menubar. Kindly review it

### CODE REVIEW

**Comment by Muhammed-Rahif** [comment]
Please resolve the conflicts.

**Comment by khushbooag4** [comment]
Kindly review it .

**Comment by Muhammed-Rahif** [comment]
@khushbooag4 there is some conflicts on this PR, please resolve it. Then I can review it.

If you don't know how to resolve it, let me know that.

Conflicts happen when your PR branch isn't up to date with base branch, which means the PR branch don't have the new changes from base branch of the repo. To get the base branch changes, you need to pull the changes. 
Hope you know that open source standards on this, if don't, let me.... 

And please make a new branch for each PR rather than default branch (in this case its `master`), for more info read the [CONTRIBUTING.md](https://github.com/Muhammed-Rahif/Notepad/blob/master/CONTRIBUTING.md).

@khushbooag4 Please tell me if you have any doubts on this.

**Comment by Muhammed-Rahif** [comment]
**This PR moved to #104.**

**Pull request closed without merging**
