### PR TITLE
feat: create drawpad component with contexts

### PR DESCRIPTION
**Pull request by Muhammed-Rahif**
Resolves :- #79 #49 

- [x] create drawing mode context
- [x] refractor : MenuBar
- [x] install 'react-canvas-draw'
- [x] create 'useWindowSize' hook

Commits :-  
- feat: create drawpad component with contexts
- feat: create shortcuts for DrawPad
- fix(shortcuts): shortcuts not working on DrawPad
- feat: DrawPad contents will be stored in localStorage
- feat: save drawings as image
- Merge branch 'origin/master' into feat/draw-pad
- Merge branch 'origin/master' into feat/draw-pad
- Merge branch 'origin/master' into feat/draw-pad
- fix: mobile-usability issues
- Merge branch 'origin/master' into feat/draw-pad

### CODE REVIEW

**Comment by Muhammed-Rahif** [comment]
@anandsimmy just review the output on browser, ignore the code review if you don't know typescript as much. The only thing I need to know, if any UI components is broken or not working well on some browsers.

**Comment by anandsimmy** [comment]
@Muhammed-Rahif I tried draw mode in safari and chrome and it looks good. great job!

**Comment by Muhammed-Rahif** [comment]
@khushbooag4 we are implemented the feature drawing, as you issued on #79

**Comment by Muhammed-Rahif** [comment]
@all-contributors please add @anandsimmy for review

**Comment by khushbooag4** [comment]
It looks god

**Comment by Muhammed-Rahif** [comment]
@all-contributors please add @khushbooag4 for review

**Pull request merged**
