### PR TITLE
Full Screen Feature Added

### PR DESCRIPTION
**Pull request by khushbooag4**
I have added the full screen mode feature on the titlebar using screenfull package

### CODE REVIEW

**Comment by Muhammed-Rahif** [comment]
@khushbooag4 there is some problems :-
- **You installed the `screenfull-react`, but you are using `screenfull` dependency in compoenent. Please remove the `screenfull-react` dependency and install `screenfull` instead.**
- **We don't need the `package-lock.json` file, instead we need `yarn.lock`. if you didn't installed yarn, do this, I'll take care of the rest:- remove the `package-lock.json`. for generating `yarn.lock`, I have workflow actions there!**

I think that will clear all issues.

**Review by Muhammed-Rahif — CHANGES_REQUESTED** [review]
@khushbooag4 there is some problems :-
- **You installed the `screenfull-react`, but you are using `screenfull` dependency in compoenent. Please remove the `screenfull-react` dependency and install `screenfull` instead.**
- **We don't need the `package-lock.json` file, instead we need `yarn.lock`. if you didn't installed yarn, do this, I'll take care of the rest:- remove the `package-lock.json`. for generating `yarn.lock`, I have workflow actions there!**

I think that will clear all issues.

**Comment by khushbooag4** [comment]
I have done what you to needed. I have remove package-lock.json and install screenfull instead of screenfull-react

**Review by Muhammed-Rahif — APPROVED** [review]
@khushbooag4 everything working... But the test case is failing because of configuration issue, let me fix that.. Everything else is fine :+1:

**Comment by Muhammed-Rahif** [comment]
Jest config updated, now test cases are passing!

**Comment by Muhammed-Rahif** [comment]
@all-contributors please add @khushbooag4 for code

**Pull request merged**
